### ISSUE TITLE
It doesn't seem to like signatures on pattern synonyms:

### ISSUE THREAD

**Issue by ekmett** [rubik/argon#14]
src/Concurrent/Internal/Counted.hs
    	error: 27:1 Invalid type signature: pattern (:+) :: a -> Counted a -> Counted a

https://github.com/ekmett/concurrent/blob/d987ebf158a4d56caeeca587a521b65dfd3b6281/src/Concurrent/Internal/Counted.hs#L27

**Comment by rubik** [comment]
Thanks for the report! I'll look into it.

**Comment by rubik** [comment]
I think that CPP somehow is messing up the code. The following raises the error:
```
{-# LANGUAGE CPP #-}
#ifndef HLINT
{-# LANGUAGE ViewPatterns #-}
#endif
{-# LANGUAGE PatternSynonyms #-}

data Counted a = Counted Int [a]
               deriving (Functor, Traversable, Eq, Ord, Read, Show)

pattern (:+) :: () => () => a -> Counted a -> Counted a
pattern a :+ as <- Counted (subtract 1 -> i) (a : (Counted i -> as)) where
  a :+ Counted i as = Counted (i+1) (a:as)
```
while this one does not
```
{-# LANGUAGE ViewPatterns #-}
{-# LANGUAGE PatternSynonyms #-}

data Counted a = Counted Int [a]
               deriving (Functor, Traversable, Eq, Ord, Read, Show)

pattern (:+) :: () => () => a -> Counted a -> Counted a
pattern a :+ as <- Counted (subtract 1 -> i) (a : (Counted i -> as)) where
  a :+ Counted i as = Counted (i+1) (a:as)
```

I also noticed that CPP-related errors sometimes show up when the syntax is correct.

**Comment by rubik** [comment]
Now all files from the lens and concurrent packages are parsed correctly.
The *only* exception to this rule are C macros of the form ``__MIN_VERSION_{package}__`` which are provided by Cabal and I have yet to figure out how to support them.

**Comment by ekmett** [comment]
One option for MIN_VERSION_foo would be to fake them by rummaging through
the package database (or just the output of ghc-pkg list) and taking the
latest version of each as a conservative over-approximation.

That doesn't really help scenarios like stack that avoid using the global
package DB though, there you'd need to find the current sandbox.

**Comment by rubik** [comment]
I was hoping that the cabal library had some functions to work with this. I have yet to investigate the issue though.
