### ISSUE TITLE
ExplicitForAll errors, even when RankNTypes is enabled

### ISSUE THREAD

**Issue by meditans** [rubik/argon#28]
Let's investigate the last two errors remaining when supplying the `src` directory of [`hint`](https://github.com/mvdan/hint). For reference, I'm running `argon` with the command

    argon --min 10 --cabal-macros $(stack path --dist-dir)/build/autogen/cabal_macros.h --cabal-file hint.cabal src

where the `--min 10` is a hack to see only the errors.
After the corrections we talked about in the previous post, we were left with:

    src/Hint/Base.hs
    	error: 94:14 Illegal symbol '.' in type
    Perhaps you intended to use RankNTypes or a similar language
    extension to enable explicit-forall syntax: forall <tvs>. <type>
    src/Hint/Configuration.hs
    	error: 59:20 Not a data constructor: ‘forall’
    Perhaps you intended to use ExistentialQuantification

This strongly hints that the problem is with `ExplicitForAll`, and indeed, if I add `ExplicitForAll` to the cabal file, the sources are all processed without errors. However, the sources contained also `Rank2Types` (which I switched for `RankNTypes` with no observable difference), which according to common experience (and [this useful diagram](http://i.imgur.com/drL9wnc.png)) should imply `ExplicitForAll`.

So the question is: how could argon be convinced to load also that extension? Where does the mismatch with the behavior of the compiler happen (the compiler doesn't throw an error)?

*UPDATE* Massimo told me on irc that [here](https://github.com/ghc/ghc/blob/master/compiler/main/DynFlags.hs#L3696-L3748)'s where ghc implements the extension dependencies.

**Comment by rubik** [comment]
Nice work! It could be that Argon is setting extensions in a wrong way and `impliedXFlags` is never called.
The link to the GHC source is super useful! :+1:

**Comment by rubik** [comment]
Got it! Argon should use `setExtensionFlag'` instead of `xopt_set`. The former is exactly what we need:
https://github.com/ghc/ghc/blob/master/compiler/main/DynFlags.hs#L4175
because it calls `impliedXFlags` automatically.

The problem is.... it isn't exported :anguished: And we cannot even implement it ourselves, because neither `impliedXFlags` is exported. We would then to copy everything, but I really dislike this solution as implied extensions change between different GHC versions.

**Comment by meditans** [comment]
That is unfortunate, indeed. So, the copying solution is indeed ugly, but is probably the only thing we can hope to have before lobbying for an export of that function in ghc, and than it would be only compilable with the last ghc in any case.

A question comes to mind, though: doesn't cabal have the same problem? How does it do it? Is there a way to use a more high level exported function from the ghc library, letting it doing the work?

**Comment by rubik** [comment]
That's an interesting point, I'll check the Cabal source to see if I can find something.

**Comment by meditans** [comment]
Which functions in particular could be of help in the [dynflags](https://www.stackage.org/haddock/lts-6.3/ghc-7.10.3/DynFlags.html#g:5) module? Are the correct extensions invoked in, e.g., `parseDynamicFlagsCmdLine`?

**Comment by rubik** [comment]
Yes, I belive `parseDynamicFlagsCmdLine` could work. It's just a wrapper

    parseDynamicFlagsCmdLine = parseDynamicFlagsFull flagsAll True

but `flagsAll` contains the flags related to the extensions as well. I just have to test it.

**Comment by rubik** [comment]
Hooray! I confirm that using `parseDynamicFlagsCmdLine` works! It's a pretty ugly hack though, there has to be a better solution...

**Comment by meditans** [comment]
It seems that the modification works; in the end, I invoke the program on `hint` (and I get no errors) with:

    argon --cabal-macros $(stack path --dist-dir)/build/autogen/cabal_macros.h --cabal-file hint.cabal src

I saw the commit, it doesn't seem to bad. Why do you feel it's pretty ugly? The better solution would probably be the export of the `setExtensionFlag'` function, right? If that's indeed the case, I checked with the folks in the `#ghc` channel and they proposed me to attach the proposed patch to a `trac` ticket for `ghc`.

I put that on hold since you were testing `parseDynamicFlagCommandLine`, but do you feel that that modification would be still useful/lead to better code?

**Comment by rubik** [comment]
Well I find that the current solution has both some advantages and disadvantages. The main advantage I see is that since we're building a command line, the behaviour will always be the same as the GHC binary.

Still, I don't think it's the right way to proceed. Compare the current solution:
```haskell
(dflags1,_,_) <- GHC.parseDynamicFlagsCmdLine dflags0
    [GHC.L GHC.noSrcSpan ("-X" ++ e) | e <- exts conf]
```
with
```haskell
let dflags1 = foldr setExtensionFlag' dflags0 $ exts conf  -- not tested, but you get the point
```
In the first case we're doing useless work that will be undone by GHC. Instead, if `setExtensionFlag'` becomes part of the public API, it will be pretty much guaranteed that it will not break randomly at some point. Moreover, I just don't see why `setGeneralFlag'` is exported and `setExtensionFlag'` is not.

**Comment by meditans** [comment]
The right thing to do is exporting `setExtensionFlag'` in ghc. Our long game would be introducing it when we don't need to support the old versions anymore (a very long game).

I'll try to write a patch later. For now, I have other questions on the code, but I'll open a new issue :)
