### ISSUE TITLE
Stack Support

### ISSUE THREAD

**Issue by xanderdunn** [rubik/argon#31]
It appears argon can't currently be dependency resolved by the default, stable Stack.  To build it with a Stack project requires adding this to stack.yml: `extra-deps: [pipes-files-0.1.1, hierarchy-0.3.1, posix-paths-0.2.1.0]`.

**Comment by rubik** [comment]
Yes, that's because the maintainer of those dependencies cannot stay up-to-date with Stackage. It was discussed here https://github.com/fpco/stackage/issues/1215, and although some maintainers updated their libraries, some did not.

So thatìs why currently Argon cannot be in Stackage.
