### ISSUE TITLE
Provide an explanation about how cyclomatic complexity is measured

### ISSUE THREAD

**Issue by capitanbatata** [rubik/argon#32]
Hi,

It'd be nice to have an explanation about what the different figures (1, 5, 10) actually mean. Cyclomatic complexity is usually defined for imperative programs, but I could not find what is the definition of cyclomatic complexity that `argon` uses. If you have a reference to a paper or article I can help with updating the readme.

**Comment by capitanbatata** [comment]
Thanks for replying Michele!

I've cloned you're repo last weekend, and I'm updating it to the latest stack LTS. So I might submit a pull request soon. I don't know if adding me as a mantainer will make things easier, but we could wait till I make the PR.

My intention is to use Argon inside an engine for code-climate. 

Thanks for the references to the way you calculate the cyclomatic complexity. I have one question about the code above though: do you add any complexity in the case of recursion? Or what about calling other functions?

**Comment by rubik** [comment]
Excellent, I'll wait for the PR then.

No, recursion does not impact CC, and neither does calling other functions. This is because the original definition of McCabe states that CC is the number of possible path that the code execution can take. If one isn't using callbacks, functions don't have an impact on this.

**Comment by capitanbatata** [comment]
Thanks for the explanation Michele.

I'm trying to put the `hierarchy` and `pipes-files` into Stackage again, and then I'll submit the PR to `argon`, so it might take a while before the PR comes through.

**Comment by rubik** [comment]
Ok, there's no hurry. Yes Argon was in Stackage but then it was removed due to its dependencies.
