### ISSUE TITLE
Alternatives or updating argon

### ISSUE THREAD

**Issue by ivanperez-keera** [rubik/argon#39]
Hi,

I'm trying to use argon with a Haskell codebase to document some program requirements.

The status right now is that it only compiles with GHC < 8.

Is it possible to update it, or are there good alternatives that could be documented in the README for people who land here?

**Comment by nh2** [comment]
@ivanperez-keera Looks like GHC 8 support is in https://github.com/rubik/argon/pull/33 but no Hackage release was made.

**Comment by ivanperez-keera** [comment]
Thanks, @nh2 . Maybe what we need is then to request a new release of argon.

**Comment by rubik** [comment]
@ivanperez-keera @nh2 Thanks for the heads up, I uploaded the current version as 0.4.2.0 to Hackage. It's tested on GHC 8.2.2.
